# Generated by Django 5.1.4 on 2025-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ambulans',
                'verbose_name_plural': 'Ambulanslar',
            },
        ),
    ]
