# Generated by Django 5.1.4 on 2025-02-01 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulance',
            options={'verbose_name': 'Ambulance', 'verbose_name_plural': 'Ambulances'},
        ),
        migrations.AddField(
            model_name='ambulance',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
    model_name='ambulance',
    name='created_at',
    field=models.DateTimeField(auto_now_add=True),  # default=1 kaldırıldı
        ),

        migrations.AddField(
            model_name='ambulance',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Plate'),  # default=1 kaldırıldı
        ),

        migrations.AddField(
            model_name='ambulance',
            name='ambulance_type',
            field=models.CharField(choices=[('normal', 'Normal Ambulance'), ('intensive_care', 'Intensive Care Ambulance'), ('special', 'Specially Equipped Ambulance')], max_length=20, verbose_name='Ambulance Type'),  # default=2 kaldırıldı
        ),
        migrations.AddField(
            model_name='ambulance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='traffic_code',
            field=models.CharField(max_length=10, verbose_name='Traffic Code'),
        ),
        migrations.CreateModel(
            name='StandardEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_stretcher', models.BooleanField(default=False, verbose_name='Main Stretcher')),
                ('main_stretcher_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Main Stretcher Count')),
                ('combination_stretcher', models.BooleanField(default=False, verbose_name='Combination Stretcher')),
                ('combination_stretcher_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Combination Stretcher Count')),
                ('vacuum_stretcher', models.BooleanField(default=False, verbose_name='Vacuum Stretcher')),
                ('vacuum_stretcher_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Vacuum Stretcher Count')),
                ('scoop_stretcher', models.BooleanField(default=False, verbose_name='Scoop Stretcher')),
                ('scoop_stretcher_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Scoop Stretcher Count')),
                ('spine_board', models.BooleanField(default=False, verbose_name='Spine Board')),
                ('spine_board_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Spine Board Count')),
                ('traction_splint_set', models.BooleanField(default=False, verbose_name='Traction Splint Set')),
                ('traction_splint_set_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Traction Splint Set Count')),
                ('inflatable_splint_set', models.BooleanField(default=False, verbose_name='Inflatable Splint Set')),
                ('inflatable_splint_set_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Inflatable Splint Set Count')),
                ('cervical_collar_set', models.BooleanField(default=False, verbose_name='Cervical Collar Set')),
                ('cervical_collar_set_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Cervical Collar Set Count')),
                ('ked_rescue_vest', models.BooleanField(default=False, verbose_name='KED Rescue Vest')),
                ('ked_rescue_vest_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='KED Rescue Vest Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standard_equipment', to='emergency.ambulance', verbose_name='Ambulance')),
            ],
            options={
                'verbose_name': 'Standard Equipment',
                'verbose_name_plural': 'Standard Equipment',
            },
        ),
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, unique=True, verbose_name='Station Code')),
                ('station_name', models.CharField(max_length=100, verbose_name='Station Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Neighborhood')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('building_no', models.CharField(max_length=20, verbose_name='Building No')),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Floor')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postal Code')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulances', models.ManyToManyField(blank=True, related_name='stations', to='emergency.ambulance', verbose_name='Ambulances')),
            ],
            options={
                'verbose_name': 'Station Info',
                'verbose_name_plural': 'Station Information',
            },
        ),
    ]
