# Generated by Django 5.1.4 on 2025-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_alter_ambulance_options_ambulance_active_and_more'),
    ]

    operations = [
    ]
