# Generated by Django 5.1.6 on 2025-02-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20250201_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='traffic_code',
        ),
    ]
