# Generated by Django 5.1.6 on 2025-02-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_remove_ambulance_traffic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationinfo',
            name='district',
        ),
    ]
